#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutomationController

#include "Basic.hpp"

#include "AutomationController_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class AutomationController.AutomationControllerSettings
// 0x0050 (0x0078 - 0x0028)
class UAutomationControllerSettings final : public UObject
{
public:
	TArray<struct FAutomatedTestGroup>            Groups;                                            // 0x0028(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	bool                                          bSuppressLogErrors;                                // 0x0038(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuppressLogWarnings;                              // 0x0039(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bElevateLogWarningsToErrors;                       // 0x003A(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         SuppressedLogCategories;                           // 0x0040(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	bool                                          bKeepPIEOpen;                                      // 0x0050(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoExpandSingleItemSubgroups;                    // 0x0051(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSortTestsByFailure;                               // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPruneLogsOnSuccess;                               // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTreatLogWarningsAsTestErrors;                     // 0x0054(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CheckTestIntervalSeconds;                          // 0x0058(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GameInstanceLostTimerSeconds;                      // 0x005C(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 TelemetryDirectory;                                // 0x0060(0x0010)(ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResetTelemetryStorageOnNewSession;                // 0x0070(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AutomationControllerSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AutomationControllerSettings")
	}
	static class UAutomationControllerSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAutomationControllerSettings>();
	}
};

SDK_NAMESPACE_END
