#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AvalancheTag

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct AvalancheTag.AvaTag
// 0x0008 (0x0008 - 0x0000)
struct FAvaTag final
{
public:
	class FName                                   TagName;                                           // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct AvalancheTag.AvaTagId
// 0x0010 (0x0010 - 0x0000)
struct FAvaTagId final
{
public:
	struct FGuid                                  ID;                                                // 0x0000(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};

// ScriptStruct AvalancheTag.AvaTagAlias
// 0x0018 (0x0018 - 0x0000)
struct FAvaTagAlias final
{
public:
	class FName                                   AliasName;                                         // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FAvaTagId>                      TagIds;                                            // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct AvalancheTag.AvaTagHandle
// 0x0018 (0x0018 - 0x0000)
struct FAvaTagHandle final
{
public:
	class UAvaTagCollection*                      Source;                                            // 0x0000(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	struct FAvaTagId                              TagId;                                             // 0x0008(0x0010)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct AvalancheTag.AvaTagHandleContainer
// 0x0018 (0x0018 - 0x0000)
struct FAvaTagHandleContainer final
{
public:
	class UAvaTagCollection*                      Source;                                            // 0x0000(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	TArray<struct FAvaTagId>                      TagIds;                                            // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPrivate)
};

// ScriptStruct AvalancheTag.AvaTagSoftHandle
// 0x0038 (0x0038 - 0x0000)
struct FAvaTagSoftHandle final
{
public:
	TSoftObjectPtr<class UAvaTagCollection>       Source;                                            // 0x0000(0x0028)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAvaTagId                              TagId;                                             // 0x0028(0x0010)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_NAMESPACE_END
