#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BotSpawner

#include "Basic.hpp"

#include "BP_BotSpawner_classes.hpp"
#include "BP_BotSpawner_parameters.hpp"


namespace SDK
{

// Function BP_BotSpawner.BP_BotSpawner_C.SpawnBot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BotSpawner_C::SpawnBot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotSpawner_C", "SpawnBot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BotSpawner.BP_BotSpawner_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BotSpawner_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotSpawner_C", "ReceiveTick");

	Params::BP_BotSpawner_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotSpawner.BP_BotSpawner_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BotSpawner_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotSpawner_C", "ReceiveEndPlay");

	Params::BP_BotSpawner_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotSpawner.BP_BotSpawner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BotSpawner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotSpawner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BotSpawner.BP_BotSpawner_C.ExecuteUbergraph_BP_BotSpawner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BotSpawner_C::ExecuteUbergraph_BP_BotSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotSpawner_C", "ExecuteUbergraph_BP_BotSpawner");

	Params::BP_BotSpawner_C_ExecuteUbergraph_BP_BotSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

