#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OrbitalCamera

#include "Basic.hpp"

#include "BP_OrbitalCamera_classes.hpp"
#include "BP_OrbitalCamera_parameters.hpp"


namespace SDK
{

// Function BP_OrbitalCamera.BP_OrbitalCamera_C.SetOrbitDistance
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InDistance                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_OrbitalCamera_C::SetOrbitDistance(double InDistance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OrbitalCamera_C", "SetOrbitDistance");

	Params::BP_OrbitalCamera_C_SetOrbitDistance Parms{};

	Parms.InDistance = InDistance;

	UObject::ProcessEvent(Func, &Parms);
}

}

