#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StationaryAggroAI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Tyr_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StationaryAggroAI.BP_StationaryAggroAI_C
// 0x0040 (0x0420 - 0x03E0)
class ABP_StationaryAggroAI_C final : public ATyrAIControllerBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ATyrWheeledVehiclePawnBase*             TankPawn;                                          // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<struct FTimerHandle>                   Timers;                                            // 0x03F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bFoundTarget;                                      // 0x0400(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_401[0x3];                                      // 0x0401(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ThrottleCheckTime;                                 // 0x0404(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EnemyCheckTime;                                    // 0x0408(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40C[0x4];                                      // 0x040C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATyrWheeledVehiclePawnBase*             FoundEnemy;                                        // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         FireCheckTime;                                     // 0x0418(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceivePossess(class APawn* PossessedPawn);
	void ReceiveDestroyed();
	void OnSpottedChanged(bool bIsSpotted);
	void OnDeath(class AActor* OwningActor, class AActor* KillingActor, const struct FCombatLogData& CombatLogData);
	void FireCheck();
	void ExecuteUbergraph_BP_StationaryAggroAI(int32 EntryPoint);
	void CheckForEnemy();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StationaryAggroAI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StationaryAggroAI_C")
	}
	static class ABP_StationaryAggroAI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StationaryAggroAI_C>();
	}
};
DUMPER7_ASSERTS_ABP_StationaryAggroAI_C;

}

