#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_DebugUtils

#include "Basic.hpp"

#include "BPFL_DebugUtils_classes.hpp"
#include "BPFL_DebugUtils_parameters.hpp"


namespace SDK
{

// Function BPFL_DebugUtils.BPFL_DebugUtils_C.GetMockEndGameStats
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FBP_EndGameStats*                OutMockStats                                           (Parm, OutParm, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::GetMockEndGameStats(class UObject* __WorldContext, struct FBP_EndGameStats* OutMockStats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "GetMockEndGameStats");

	Params::BPFL_DebugUtils_C_GetMockEndGameStats Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (OutMockStats != nullptr)
		*OutMockStats = std::move(Parms.OutMockStats);
}


// Function BPFL_DebugUtils.BPFL_DebugUtils_C.TempShouldUseOldVFXFlow
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   OutValue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::TempShouldUseOldVFXFlow(class UObject* __WorldContext, bool* OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "TempShouldUseOldVFXFlow");

	Params::BPFL_DebugUtils_C_TempShouldUseOldVFXFlow Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (OutValue != nullptr)
		*OutValue = Parms.OutValue;
}

}

