#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CDE_MenuCameras

#include "Basic.hpp"

#include "CDE_MenuCameras_classes.hpp"
#include "CDE_MenuCameras_parameters.hpp"


namespace SDK
{

// Function CDE_MenuCameras.CDE_MenuCameras_C.RunCameraDirector
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          EvaluationContextOwner                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FBlueprintCameraDirectorEvaluationParams&Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UCDE_MenuCameras_C::RunCameraDirector(float DeltaTime, class UObject* EvaluationContextOwner, const struct FBlueprintCameraDirectorEvaluationParams& Params_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CDE_MenuCameras_C", "RunCameraDirector");

	Params::CDE_MenuCameras_C_RunCameraDirector Parms{};

	Parms.DeltaTime = DeltaTime;
	Parms.EvaluationContextOwner = EvaluationContextOwner;
	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CDE_MenuCameras.CDE_MenuCameras_C.ExecuteUbergraph_CDE_MenuCameras
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCDE_MenuCameras_C::ExecuteUbergraph_CDE_MenuCameras(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CDE_MenuCameras_C", "ExecuteUbergraph_CDE_MenuCameras");

	Params::CDE_MenuCameras_C_ExecuteUbergraph_CDE_MenuCameras Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

