#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Constraint

#include "Basic.hpp"

#include "AnimationCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ControlRig_structs.hpp"
#include "ControlRig_classes.hpp"


SDK_NAMESPACE_START

// RigVMBlueprintGeneratedClass Constraint.Constraint_C
// 0x0058 (0x0BC8 - 0x0B70)
class UConstraint_C final : public UControlRig
{
public:
	bool                                          Parent;                                            // 0x0B70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Position;                                          // 0x0B71(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Rotation;                                          // 0x0B72(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Scale;                                             // 0x0B73(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Aim;                                               // 0x0B74(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B75[0x3];                                      // 0x0B75(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                AimAxis;                                           // 0x0B78(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                AimUpAxis;                                         // 0x0B90(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EControlRigVectorKind                         AimUpKind;                                         // 0x0BA8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Maintain_Offset;                                   // 0x0BA9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Active;                                            // 0x0BAA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Debug;                                             // 0x0BAB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransformFilter                       ParentConstraint_Filter;                           // 0x0BAC(0x0009)(Edit, BlueprintVisible, NoDestructor)
	struct FFilterOptionPerAxis                   PositionConstraint_Filter;                         // 0x0BB5(0x0003)(Edit, BlueprintVisible, NoDestructor)
	struct FFilterOptionPerAxis                   RotationConstraint_Filter;                         // 0x0BB8(0x0003)(Edit, BlueprintVisible, NoDestructor)
	struct FFilterOptionPerAxis                   ScaleConstraint_Filter;                            // 0x0BBB(0x0003)(Edit, BlueprintVisible, NoDestructor)
	struct FFilterOptionPerAxis                   AimConstraint_Filter;                              // 0x0BBE(0x0003)(Edit, BlueprintVisible, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Constraint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Constraint_C")
	}
	static class UConstraint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConstraint_C>();
	}
};

SDK_NAMESPACE_END
