#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_BlockFallingDamage_LimitedDuration_Ram

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_BlockFallingDamage_LimitedDuration_Ram.GE_BlockFallingDamage_LimitedDuration_Ram_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_BlockFallingDamage_LimitedDuration_Ram_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_BlockFallingDamage_LimitedDuration_Ram_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_BlockFallingDamage_LimitedDuration_Ram_C")
	}
	static class UGE_BlockFallingDamage_LimitedDuration_Ram_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_BlockFallingDamage_LimitedDuration_Ram_C>();
	}
};
DUMPER7_ASSERTS_UGE_BlockFallingDamage_LimitedDuration_Ram_C;

}

