#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_WallTracker

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_WallTracker.GE_WallTracker_C
// 0x0008 (0x0A78 - 0x0A70)
class UGE_WallTracker_C final : public UGameplayEffect
{
public:
	class AActor*                                 TrackedWall;                                       // 0x0A70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_WallTracker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_WallTracker_C")
	}
	static class UGE_WallTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_WallTracker_C>();
	}
};
DUMPER7_ASSERTS_UGE_WallTracker_C;

}

