#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Leaderboard_Player

#include "Basic.hpp"

#include "FieldNotification_structs.hpp"
#include "Tyr_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "SlateCore_structs.hpp"
#include "SnapserPlugin_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "DataRegistry_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetScoreValue
// 0x0004 (0x0004 - 0x0000)
struct VM_Leaderboard_Player_C_GetScoreValue final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.RefreshPlayerProfile
// 0x00C8 (0x00C8 - 0x0000)
struct VM_Leaderboard_Player_C_RefreshPlayerProfile final
{
public:
	bool                                          bDidRefreshFromData;                               // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrProfilesSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrProfilesSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetProfileStringAttribute_bOutFoundField; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetProfileStringAttribute_OutString;      // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           CallFunc_GetTagFromTitleString_ReturnValue;        // 0x0034(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetTagName_ReturnValue;                   // 0x003C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrPlayerTitleData                    CallFunc_GetDataTableRowFromName_OutRow;           // 0x0048(0x0050)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetProfileStringAttribute_bOutFoundField_1; // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A[0x6];                                       // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetProfileStringAttribute_OutString_1;    // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00B0(0x0010)()
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_1; // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_2; // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_3; // 0x00C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_4; // 0x00C3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.SetUserId
// 0x0038 (0x0038 - 0x0000)
struct VM_Leaderboard_Player_C_SetUserId final
{
public:
	class FString                                 InUserId;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UTyrOnlineSubsystem*                    CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RefreshPlayerProfile_bDidRefreshFromData; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTyrOnlineUserInfo*               CallFunc_GetUserInfoForLocalPlayerIndex_ReturnValue; // 0x0020(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVM_Leaderboards_C*                     CallFunc_GetLeaderboardsViewModel_ViewModel;       // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.UpdateFromLeaderboardScore
// 0x02D8 (0x02D8 - 0x0000)
struct VM_Leaderboard_Player_C_UpdateFromLeaderboardScore final
{
public:
	struct FLeaderboardScore                      InScore;                                           // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId;             // 0x0040(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_1;           // 0x0048(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFieldNotificationId>           K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ReferenceParm)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_2;           // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFieldNotificationId>           K2Node_MakeArray_Array_1;                          // 0x0068(0x0010)(ReferenceParm)
	class FName                                   CallFunc_GetTagName_ReturnValue;                   // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDataRegistryId                        K2Node_MakeStruct_DataRegistryId;                  // 0x0080(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EDataRegistrySubsystemGetItemResult           CallFunc_FindCachedItemBP_OutResult;               // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrVehicleUIDataTableStruct           CallFunc_FindCachedItemBP_OutItem;                 // 0x0098(0x0238)(ConstParm)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcastFields_ReturnValue; // 0x02D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcastFields_ReturnValue_1; // 0x02D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x02D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_1; // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetLocalPlayerTextColor
// 0x005C (0x005C - 0x0000)
struct VM_Leaderboard_Player_C_GetLocalPlayerTextColor final
{
public:
	struct FSlateColor                            SlateColor;                                        // 0x0000(0x0014)(Parm, OutParm)
	bool                                          Temp_bool_Variable;                                // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetRankText
// 0x0020 (0x0020 - 0x0000)
struct VM_Leaderboard_Player_C_GetRankText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0010(0x0010)()
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetRowBackerColor
// 0x004C (0x004C - 0x0000)
struct VM_Leaderboard_Player_C_GetRowBackerColor final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SafeModulo_IntInt_ReturnValue;            // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x003C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetScoreText
// 0x0020 (0x0020 - 0x0000)
struct VM_Leaderboard_Player_C_GetScoreText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0010(0x0010)()
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
