#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_PlayerProfile

#include "Basic.hpp"

#include "VM_PlayerProfile_classes.hpp"
#include "VM_PlayerProfile_parameters.hpp"


SDK_NAMESPACE_START

// Function VM_PlayerProfile.VM_PlayerProfile_C.ClearPlayerTitle
// (Public, BlueprintCallable, BlueprintEvent)

void UVM_PlayerProfile_C::ClearPlayerTitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_PlayerProfile_C", "ClearPlayerTitle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_PlayerProfile.VM_PlayerProfile_C.SetPlayerTitle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InTitleTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_PlayerProfile_C::SetPlayerTitle(const struct FGameplayTag& InTitleTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_PlayerProfile_C", "SetPlayerTitle");

	Params::VM_PlayerProfile_C_SetPlayerTitle Parms{};

	Parms.InTitleTag = std::move(InTitleTag);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
