#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Scoreboard_Player

#include "Basic.hpp"

#include "DataRegistry_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "Tyr_structs.hpp"
#include "Tyr_classes.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_Scoreboard_Player.VM_Scoreboard_Player_C
// 0x0160 (0x01C8 - 0x0068)
class UVM_Scoreboard_Player_C final : public UTyrViewModel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0068(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   PlayerId;                                          // 0x0070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Matchdetailsid;                                    // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 LocalPartyId;                                      // 0x0080(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   VehicleId;                                         // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   PlayerName;                                        // 0x0098(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   TankName;                                          // 0x00A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TSoftObjectPtr<class UMaterialInterface>      PilotPortrait;                                     // 0x00B8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FText                                   VehicleName;                                       // 0x00E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTag                           VehicleClass;                                      // 0x00F0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         DamageDone;                                        // 0x00F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DamageBlocked;                                     // 0x00FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         AssistDamage;                                      // 0x0100(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Kills;                                             // 0x0104(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAlive;                                           // 0x0108(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInParty;                                         // 0x0109(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLocalPlayer;                                     // 0x010A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10B[0x5];                                      // 0x010B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrPlayerTitleData                    TitleData;                                         // 0x0110(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          HasTitle;                                          // 0x0160(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SalutedByLocalPlayer;                              // 0x0161(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SaluteRequestInflight;                             // 0x0162(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_163[0x5];                                      // 0x0163(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncAction_ListenForGameplayMessage*  SaluteAppliedListener;                             // 0x0168(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              KeystoneIcon;                                      // 0x0170(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          HasKeystone;                                       // 0x0198(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   KeystoneName;                                      // 0x01A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   KeystoneDesc;                                      // 0x01B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsCustomGame;                                      // 0x01C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSpectator;                                       // 0x01C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateFromUserRecord(const struct FMatchUserRecord& InMatchUserRecord, class FName InMatchDetailsId, const class FString& InLocalPartyId);
	void SetupSaluteListener(class FName InMatchDetailsId);
	void SetIsLocalPlayer(class FName InLocalPlayerId);
	void ResolveKeystoneFromTag(const struct FGameplayTag& InKeystoneTag);
	void OnMessageReceived_D33111174D222E7BD6091C94F71F58DE(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel);
	void OnDeinitialized();
	bool IsInLocalParty(const class FString& InPartyId);
	void ExecuteUbergraph_VM_Scoreboard_Player(int32 EntryPoint);

	class FText SetKillsText() const;
	void SetIsLocalPlayerText_Vehicle(struct FSlateFontInfo* SlateFontInfo) const;
	void SetIsLocalPlayerText_Numbers(struct FSlateFontInfo* SlateFontInfo) const;
	void SetIsLocalPlayerText_Name(struct FSlateFontInfo* SlateFontInfo) const;
	class FText SetDamageDoneText() const;
	class FText SetDamageBlockedText() const;
	class FText SetAssistDamageText() const;
	void IsAliveLocalPlayerColor(struct FLinearColor* LinearColor) const;
	void GetTankMipLevel(struct FTyrMaterialScalarParam* Return_Node) const;
	void GetTankDesaturation(struct FTyrMaterialScalarParam* Return_Node) const;
	ESlateVisibility GetShouldHideSalute() const;
	void GetDisplayAsSaluted(bool* bDisplayAsSaluted) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_Scoreboard_Player_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_Scoreboard_Player_C")
	}
	static class UVM_Scoreboard_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_Scoreboard_Player_C>();
	}
};

SDK_NAMESPACE_END
