#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_VehicleViewer

#include "Basic.hpp"

#include "DataRegistry_structs.hpp"
#include "Engine_structs.hpp"
#include "Tyr_classes.hpp"
#include "E_MenuCameraRig_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_VehicleViewer.VM_VehicleViewer_C
// 0x01B0 (0x0220 - 0x0070)
class UVM_VehicleViewer_C final : public UTyrGlobalViewModel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0070(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_BaseTank_Lite_C*                    SpawnedVehicle;                                    // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UVM_Vehicle_C*>                  Vehicles;                                          // 0x0080(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UVM_Vehicle_Cinematics_C*>       VehicleCinematics;                                 // 0x0090(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UVM_Vehicle_C*                          ActiveVehicle;                                     // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UVM_Vehicle_Cinematics_C*               ActiveVehicleCinematics;                           // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UVM_Vehicle_Details_C*                  ActiveVehicleDetails;                              // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UVM_Cosmetics_Vehicle_C*                ActiveVehicleCosmetics;                            // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        CameraArmorRestingPitch;                           // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraArmorRestingYaw;                             // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bHasRestrictedTurretYaw;                           // 0x00D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        TurretYawMin;                                      // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TurretYawMax;                                      // 0x00E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsDisplayingArmor;                                // 0x00E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsScreenshotMode;                                 // 0x00E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EA[0x6];                                       // 0x00EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        ZoomLevel;                                         // 0x00F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumZoomSteps;                                      // 0x00F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CameraFieldOfViewMin;                              // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraFieldOfViewMax;                              // 0x0108(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraDistanceMin;                                 // 0x0110(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraDistanceMax;                                 // 0x0118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZoomMinAngularSize;                                // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZoomMaxAngularSize;                                // 0x0128(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        VehicleSizeForZoom;                                // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UWorld>                  PendingSublevel;                                   // 0x0138(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash)
	class ULevelStreamingDynamic*                 ActiveSublevel;                                    // 0x0160(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	double                                        CameraArmorZoom;                                   // 0x0168(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraCosmeticsRestingPitch;                       // 0x0170(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraCosmeticsRestingYaw;                         // 0x0178(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraDetailsRestingPitch;                         // 0x0180(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraDetailsRestingYaw;                           // 0x0188(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRuntimeFloatCurve                     RestingZoomCurve;                                  // 0x0190(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ABP_GenericTank_Lite_C*                 GenericVehicle;                                    // 0x0218(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AddDistanceToCamera(double InDistance);
	void DestroyGenericVehicle();
	void DestroySpawnedVehicle();
	void ExecuteUbergraph_VM_VehicleViewer(int32 EntryPoint);
	void FindSpawnedVehicle(bool* bFoundVehicle, class ABP_BaseTank_Lite_C** Vehicle);
	void InitializeCameraZoomForVehicle();
	void InitializeVehicleViewModels();
	void OnBlendOut_F7B360B44160A3F951E8E3B9E9C13611(class FName NotifyName);
	void OnCompleted_F7B360B44160A3F951E8E3B9E9C13611(class FName NotifyName);
	void OnInitialized();
	void OnInitialPlayerReady();
	void OnInterrupted_F7B360B44160A3F951E8E3B9E9C13611(class FName NotifyName);
	void OnLoaded_66A96BD0493AC4818C23F1A662CB0575(TSubclassOf<class UObject> Loaded);
	void OnLoaded_B4AFCA294CC345B4F6C75EB3E6E78DEA(class UObject* Loaded);
	void OnLoaded_B75A13634012F6B8401670983F75EC58(class UObject* Loaded);
	void OnLoaded_B75A13634012F6B840167098478F4D7F(class UObject* Loaded);
	void OnNotifyBegin_F7B360B44160A3F951E8E3B9E9C13611(class FName NotifyName);
	void OnNotifyEnd_F7B360B44160A3F951E8E3B9E9C13611(class FName NotifyName);
	void OnPlayTargetAbilityMontage(TSoftObjectPtr<class UAnimMontage> AbilityMontage, class FName SectionName);
	void OnSpawnVehicle(TSoftClassPtr<class UClass> VehicleClass);
	void OnStreamVehicleLevel();
	void OnVehicleLevelReady();
	void ResetCameraZoom();
	void SetActiveVehicle(const struct FGameplayTag& InVehicleTag);
	void SetPitchAndYaw(double InYaw, double InPitch);
	void SetSpawnedVehicleHidden(bool bInShouldHide);
	void SetTurretRotation(float InYaw, float InPitch);
	void ShowArmorVisualizer(bool bInShouldShow, float InPenetration);
	void SpawnGenericVehicle();
	void SpawnTargetVehicle(const struct FGameplayTag& InVehicleTag);
	void StepCameraZoom(double InStepAmount);
	void ToggleAbilityVisuals();

	struct FGameplayTag GetActiveVehicleTag() const;
	void GetCameraPropertiesFromZoomLevel(double* DistanceFromTarget, double* FieldOfView) const;
	class UVM_Vehicle_C* GetLastActiveVehicle() const;
	void GetPitchAndYaw(double* Yaw, double* Pitch) const;
	void GetRestingPitchAndYaw(double* Yaw, double* Pitch) const;
	void GetTurretRotation(struct FVector2D* YawAndPitch) const;
	class UVM_Vehicle_Cinematics_C* GetVehicleCinematicsFromTag(const struct FGameplayTag& InVehicleTag) const;
	class UVM_Vehicle_C* GetVehicleFromTag(const struct FGameplayTag& InVehicleTag) const;
	bool IsAtRestingPitchAndYaw() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_VehicleViewer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_VehicleViewer_C")
	}
	static class UVM_VehicleViewer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_VehicleViewer_C>();
	}
};

SDK_NAMESPACE_END
