#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComparisonTable

#include "Basic.hpp"

#include "WBP_ComparisonTable_classes.hpp"
#include "WBP_ComparisonTable_parameters.hpp"


namespace SDK
{

// Function WBP_ComparisonTable.WBP_ComparisonTable_C.BndEvt__WBP_ComparisonTable_WBP_Button_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::BndEvt__WBP_ComparisonTable_WBP_Button_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "BndEvt__WBP_ComparisonTable_WBP_Button_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_ComparisonTable_C_BndEvt__WBP_ComparisonTable_WBP_Button_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_ComparisonTable_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)

void UWBP_ComparisonTable_C::BP_OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "BP_OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.ClearArrays
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ComparisonTable_C::ClearArrays()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "ClearArrays");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ComparisonTable_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.ExecuteUbergraph_WBP_ComparisonTable
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::ExecuteUbergraph_WBP_ComparisonTable(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "ExecuteUbergraph_WBP_ComparisonTable");

	Params::WBP_ComparisonTable_C_ExecuteUbergraph_WBP_ComparisonTable Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.FindFirstEmptySpot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  SlotIndex_0                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::FindFirstEmptySpot(int32* SlotIndex_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "FindFirstEmptySpot");

	Params::WBP_ComparisonTable_C_FindFirstEmptySpot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SlotIndex_0 != nullptr)
		*SlotIndex_0 = Parms.SlotIndex_0;
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.GetNextRowColumnForVehicleClassGrid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InVehicleClassTag                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UUniformGridPanel*                InGrid                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32*                                  OutRow                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  OutColumn                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::GetNextRowColumnForVehicleClassGrid(const struct FGameplayTag& InVehicleClassTag, class UUniformGridPanel* InGrid, int32* OutRow, int32* OutColumn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "GetNextRowColumnForVehicleClassGrid");

	Params::WBP_ComparisonTable_C_GetNextRowColumnForVehicleClassGrid Parms{};

	Parms.InVehicleClassTag = std::move(InVehicleClassTag);
	Parms.InGrid = InGrid;

	UObject::ProcessEvent(Func, &Parms);

	if (OutRow != nullptr)
		*OutRow = Parms.OutRow;

	if (OutColumn != nullptr)
		*OutColumn = Parms.OutColumn;
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.HideAllColumns
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ComparisonTable_C::HideAllColumns()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "HideAllColumns");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.HideColumn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SlotIndex_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              InGameplayTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::HideColumn(int32 ButtonIndex, int32 SlotIndex_0, const struct FGameplayTag& InGameplayTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "HideColumn");

	Params::WBP_ComparisonTable_C_HideColumn Parms{};

	Parms.ButtonIndex = ButtonIndex;
	Parms.SlotIndex_0 = SlotIndex_0;
	Parms.InGameplayTag = std::move(InGameplayTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.InternalSetVehicles
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UVM_Vehicle_C*>&           InVehicles                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UUniformGridPanel*                InGrid                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::InternalSetVehicles(TArray<class UVM_Vehicle_C*>& InVehicles, class UUniformGridPanel* InGrid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "InternalSetVehicles");

	Params::WBP_ComparisonTable_C_InternalSetVehicles Parms{};

	Parms.InVehicles = std::move(InVehicles);
	Parms.InGrid = InGrid;

	UObject::ProcessEvent(Func, &Parms);

	InVehicles = std::move(Parms.InVehicles);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.OnHoverHighlightRow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   HoveredIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Hover                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::OnHoverHighlightRow(int32 HoveredIndex, bool Hover)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "OnHoverHighlightRow");

	Params::WBP_ComparisonTable_C_OnHoverHighlightRow Parms{};

	Parms.HoveredIndex = HoveredIndex;
	Parms.Hover = Hover;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.OnMaxSlotsFilled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    MaxSlotsFilled                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::OnMaxSlotsFilled(bool MaxSlotsFilled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "OnMaxSlotsFilled");

	Params::WBP_ComparisonTable_C_OnMaxSlotsFilled Parms{};

	Parms.MaxSlotsFilled = MaxSlotsFilled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.PopulateButtonsArray
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ComparisonTable_C::PopulateButtonsArray()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "PopulateButtonsArray");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "PreConstruct");

	Params::WBP_ComparisonTable_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.RebuildColumns
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ComparisonTable_C::RebuildColumns()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "RebuildColumns");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.RemoveColumn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InButtonIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              InGameplayTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::RemoveColumn(int32 InButtonIndex, const struct FGameplayTag& InGameplayTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "RemoveColumn");

	Params::WBP_ComparisonTable_C_RemoveColumn Parms{};

	Parms.InButtonIndex = InButtonIndex;
	Parms.InGameplayTag = std::move(InGameplayTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.RemoveColumnClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::RemoveColumnClicked(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "RemoveColumnClicked");

	Params::WBP_ComparisonTable_C_RemoveColumnClicked Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.SetHeavyVehicles
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UVM_Vehicle_C*>&           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ComparisonTable_C::SetHeavyVehicles(TArray<class UVM_Vehicle_C*>& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "SetHeavyVehicles");

	Params::WBP_ComparisonTable_C_SetHeavyVehicles Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);

	NewParam = std::move(Parms.NewParam);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.SetLightVehicles
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UVM_Vehicle_C*>&           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ComparisonTable_C::SetLightVehicles(TArray<class UVM_Vehicle_C*>& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "SetLightVehicles");

	Params::WBP_ComparisonTable_C_SetLightVehicles Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);

	NewParam = std::move(Parms.NewParam);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.SetMediumVehicles
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UVM_Vehicle_C*>&           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ComparisonTable_C::SetMediumVehicles(TArray<class UVM_Vehicle_C*>& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "SetMediumVehicles");

	Params::WBP_ComparisonTable_C_SetMediumVehicles Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);

	NewParam = std::move(Parms.NewParam);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.SetUpStatLabels
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ComparisonTable_C::SetUpStatLabels()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "SetUpStatLabels");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.ShowColumn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NextSlotIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              InGameplayTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::ShowColumn(int32 ButtonIndex, int32 NextSlotIndex, const struct FGameplayTag& InGameplayTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "ShowColumn");

	Params::WBP_ComparisonTable_C_ShowColumn Parms{};

	Parms.ButtonIndex = ButtonIndex;
	Parms.NextSlotIndex = NextSlotIndex;
	Parms.InGameplayTag = std::move(InGameplayTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.ShowSelectedPilotStats
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InGameplayTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UWBP_Button_C*                    InButton                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::ShowSelectedPilotStats(const struct FGameplayTag& InGameplayTag, class UWBP_Button_C* InButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "ShowSelectedPilotStats");

	Params::WBP_ComparisonTable_C_ShowSelectedPilotStats Parms{};

	Parms.InGameplayTag = std::move(InGameplayTag);
	Parms.InButton = InButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComparisonTable.WBP_ComparisonTable_C.ToggleIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InButtonIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              InGameplayTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_ComparisonTable_C::ToggleIndex(int32 InButtonIndex, const struct FGameplayTag& InGameplayTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComparisonTable_C", "ToggleIndex");

	Params::WBP_ComparisonTable_C_ToggleIndex Parms{};

	Parms.InButtonIndex = InButtonIndex;
	Parms.InGameplayTag = std::move(InGameplayTag);

	UObject::ProcessEvent(Func, &Parms);
}

}

