#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Button_Filter

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Button_Filter.WBP_Button_Filter_C.SetVM_FilterOption
// 0x0028 (0x0028 - 0x0000)
struct WBP_Button_Filter_C_SetVM_FilterOption final
{
public:
	class UVM_FilterOption_C*                     ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;      // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_Button_Filter.WBP_Button_Filter_C.ExecuteUbergraph_WBP_Button_Filter
// 0x0004 (0x0004 - 0x0000)
struct WBP_Button_Filter_C_ExecuteUbergraph_WBP_Button_Filter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

