#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PostGame_Score

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_PostGame_Score.WBP_PostGame_Score_C.SetVM_Scoreboard
// 0x0028 (0x0028 - 0x0000)
struct WBP_PostGame_Score_C_SetVM_Scoreboard final
{
public:
	class UVM_Scoreboard_C*                       ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;      // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_PostGame_Score.WBP_PostGame_Score_C.__ed31dd71-4442-3c14-e9ba-619c323253be_SourceToDest
// 0x002C (0x002C - 0x0000)
struct WBP_PostGame_Score_C___ed31dd71_4442_3c14_e9ba_619c323253be_SourceToDest final
{
public:
	struct FSlateColor                            ReturnValue;                                       // 0x0000(0x0014)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_DidWinMatch_InDidWin;                     // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            CallFunc_SelectSlateColor_ReturnValue;             // 0x0018(0x0014)()
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
