#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modal_OverviewInfo

#include "Basic.hpp"

#include "WBP_Modal_OverviewInfo_classes.hpp"
#include "WBP_Modal_OverviewInfo_parameters.hpp"


namespace SDK
{

// Function WBP_Modal_OverviewInfo.WBP_Modal_OverviewInfo_C.ExecuteUbergraph_WBP_Modal_OverviewInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modal_OverviewInfo_C::ExecuteUbergraph_WBP_Modal_OverviewInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modal_OverviewInfo_C", "ExecuteUbergraph_WBP_Modal_OverviewInfo");

	Params::WBP_Modal_OverviewInfo_C_ExecuteUbergraph_WBP_Modal_OverviewInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modal_OverviewInfo.WBP_Modal_OverviewInfo_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modal_OverviewInfo_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modal_OverviewInfo_C", "PreConstruct");

	Params::WBP_Modal_OverviewInfo_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modal_OverviewInfo.WBP_Modal_OverviewInfo_C.SetUpOverviewInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTankDataTableStruct&      InDTTankData                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Modal_OverviewInfo_C::SetUpOverviewInfo(const struct FTankDataTableStruct& InDTTankData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modal_OverviewInfo_C", "SetUpOverviewInfo");

	Params::WBP_Modal_OverviewInfo_C_SetUpOverviewInfo Parms{};

	Parms.InDTTankData = std::move(InDTTankData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modal_OverviewInfo.WBP_Modal_OverviewInfo_C.UpdateLoadoutInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_StatWidget_C*                InCategory                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// double                                  InStatBaseFloat                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      InStatBaseText                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      InStatTextSuffix                                       (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Modal_OverviewInfo_C::UpdateLoadoutInfo(class UWBP_StatWidget_C* InCategory, double InStatBaseFloat, const class FText& InStatBaseText, const class FText& InStatTextSuffix)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modal_OverviewInfo_C", "UpdateLoadoutInfo");

	Params::WBP_Modal_OverviewInfo_C_UpdateLoadoutInfo Parms{};

	Parms.InCategory = InCategory;
	Parms.InStatBaseFloat = InStatBaseFloat;
	Parms.InStatBaseText = std::move(InStatBaseText);
	Parms.InStatTextSuffix = std::move(InStatTextSuffix);

	UObject::ProcessEvent(Func, &Parms);
}

}

