#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUD_TeamTileEntry

#include "Basic.hpp"

#include "WBP_HUD_TeamTileEntry_classes.hpp"
#include "WBP_HUD_TeamTileEntry_parameters.hpp"


namespace SDK
{

// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "BP_OnItemExpansionChanged");

	Params::WBP_HUD_TeamTileEntry_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "BP_OnItemSelectionChanged");

	Params::WBP_HUD_TeamTileEntry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.CleanupMessageListeners
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::CleanupMessageListeners()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "CleanupMessageListeners");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.ExecuteUbergraph_WBP_HUD_TeamTileEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::ExecuteUbergraph_WBP_HUD_TeamTileEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "ExecuteUbergraph_WBP_HUD_TeamTileEntry");

	Params::WBP_HUD_TeamTileEntry_C_ExecuteUbergraph_WBP_HUD_TeamTileEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.Get_AllyBorder_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_HUD_TeamTileEntry_C::Get_AllyBorder_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "Get_AllyBorder_Visibility");

	Params::WBP_HUD_TeamTileEntry_C_Get_AllyBorder_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.GetMyPartyVisibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_HUD_TeamTileEntry_C::GetMyPartyVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "GetMyPartyVisibility");

	Params::WBP_HUD_TeamTileEntry_C_GetMyPartyVisibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnListItemObjectSet");

	Params::WBP_HUD_TeamTileEntry_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnLoaded_6B422B98496AF4CC2239C98E823C10C6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::OnLoaded_6B422B98496AF4CC2239C98E823C10C6(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnLoaded_6B422B98496AF4CC2239C98E823C10C6");

	Params::WBP_HUD_TeamTileEntry_C_OnLoaded_6B422B98496AF4CC2239C98E823C10C6 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnMessageReceived_170109EA4719075572FFA7B9C1768F28
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::OnMessageReceived_170109EA4719075572FFA7B9C1768F28(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnMessageReceived_170109EA4719075572FFA7B9C1768F28");

	Params::WBP_HUD_TeamTileEntry_C_OnMessageReceived_170109EA4719075572FFA7B9C1768F28 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnMessageReceived_70E5876C4D11639B4A1A639612F58CC7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::OnMessageReceived_70E5876C4D11639B4A1A639612F58CC7(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnMessageReceived_70E5876C4D11639B4A1A639612F58CC7");

	Params::WBP_HUD_TeamTileEntry_C_OnMessageReceived_70E5876C4D11639B4A1A639612F58CC7 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnMessageReceived_F6989EA64E04B66E8D7D598E15393321
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::OnMessageReceived_F6989EA64E04B66E8D7D598E15393321(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnMessageReceived_F6989EA64E04B66E8D7D598E15393321");

	Params::WBP_HUD_TeamTileEntry_C_OnMessageReceived_F6989EA64E04B66E8D7D598E15393321 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.OnUpdateState
// (BlueprintCallable, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::OnUpdateState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "OnUpdateState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.PlayDestroyedAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HUD_TeamTileEntry_C::PlayDestroyedAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "PlayDestroyedAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.SetEnemySpottedVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInIsSpotted                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::SetEnemySpottedVisibility(bool bInIsSpotted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "SetEnemySpottedVisibility");

	Params::WBP_HUD_TeamTileEntry_C_SetEnemySpottedVisibility Parms{};

	Parms.bInIsSpotted = bInIsSpotted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.SetPlayerViewModels
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     InPlayerState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::SetPlayerViewModels(class APlayerState* InPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "SetPlayerViewModels");

	Params::WBP_HUD_TeamTileEntry_C_SetPlayerViewModels Parms{};

	Parms.InPlayerState = InPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.SetVisualsToDestroyed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInIsDestroyed                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::SetVisualsToDestroyed(bool bInIsDestroyed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "SetVisualsToDestroyed");

	Params::WBP_HUD_TeamTileEntry_C_SetVisualsToDestroyed Parms{};

	Parms.bInIsDestroyed = bInIsDestroyed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.SetVM_PlayerHealth
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_PlayerHealth_C*               ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::SetVM_PlayerHealth(class UVM_PlayerHealth_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "SetVM_PlayerHealth");

	Params::WBP_HUD_TeamTileEntry_C_SetVM_PlayerHealth Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.UpdateListItem
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          InListItemObject                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::UpdateListItem(class UObject* InListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "UpdateListItem");

	Params::WBP_HUD_TeamTileEntry_C_UpdateListItem Parms{};

	Parms.InListItemObject = InListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.UpdatePlayerViewModels
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ATyrPlayerStateBase*              PlayerState_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_TeamTileEntry_C::UpdatePlayerViewModels(class ATyrPlayerStateBase* PlayerState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "UpdatePlayerViewModels");

	Params::WBP_HUD_TeamTileEntry_C_UpdatePlayerViewModels Parms{};

	Parms.PlayerState_0 = PlayerState_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.__940e9190-49ed-1752-b29f-86b2b0fa486a_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_HUD_TeamTileEntry_C::__940e9190_49ed_1752_b29f_86b2b0fa486a_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "__940e9190-49ed-1752-b29f-86b2b0fa486a_SourceToDest");

	Params::WBP_HUD_TeamTileEntry_C___940e9190_49ed_1752_b29f_86b2b0fa486a_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.__e50dadb6-4139-f9b8-d510-fbac1ddd268e_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_HUD_TeamTileEntry_C::__e50dadb6_4139_f9b8_d510_fbac1ddd268e_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "__e50dadb6-4139-f9b8-d510-fbac1ddd268e_SourceToDest");

	Params::WBP_HUD_TeamTileEntry_C___e50dadb6_4139_f9b8_d510_fbac1ddd268e_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.GetAllyBorderColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_HUD_TeamTileEntry_C::GetAllyBorderColor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "GetAllyBorderColor");

	Params::WBP_HUD_TeamTileEntry_C_GetAllyBorderColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.GetEnemySpottedOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_HUD_TeamTileEntry_C::GetEnemySpottedOpacity() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "GetEnemySpottedOpacity");

	Params::WBP_HUD_TeamTileEntry_C_GetEnemySpottedOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_HUD_TeamTileEntry.WBP_HUD_TeamTileEntry_C.GetPlayerNameColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_HUD_TeamTileEntry_C::GetPlayerNameColor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_TeamTileEntry_C", "GetPlayerNameColor");

	Params::WBP_HUD_TeamTileEntry_C_GetPlayerNameColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

